package commands

const (
	CREATE_DATABASE = "CREATE DATABASE"
	CREATE_SCHEMA   = "CREATE SCHEMA"
	CREATE_TABLE    = "CREATE TABLE"
	EXIST           = "IF NOT EXISTS"
	CREATE_SEQUENCE = "CREATE SEQUENCE"
)
